#!/usr/bin/env bash
cd Tshaki
echo -e "\e[33m          _____ ____  _   _    _    _  __\e[0m"
echo -e "\e[33m         |_   _/ ___|| | | |  / \  | |/ /|\e[0m"
echo -e "\e[33m           | | \___ \| |_| | / _ \ | ' /|\e[0m"
echo -e "\e[33m           | |  ___) |  _  |/ ___ \| . \|\e[0m"
echo -e "\e[33m           |_| |____/|_| |_/_/   \_\_|\_\\e[0m"
while(true) do
lua start.lua 
done